using System;
using NUnit.Framework;

[TestFixture]
public class Tests
{
    [Test]
    [TestCase("ClaClaClaClap!", Result =  4)]
    [TestCase("ClClClaClaClaClap!", Result =  6)]
    [TestCase("CCClaClClap!Clap!ClClClap!", Result =  9)]
    [TestCase("ClCCClaClaClaClCClap!CClaClap!Clap!ClClClClaClaClap!Clap!ClClCClap!Clap!ClClap!ClaCClClap!ClClap!Clap!CClClaClaClaCClaCClaClClaCCCClaClap!Clap!ClaClaClap!ClaClap!CClap!Clap!ClClap!", Result =  61)]
    [TestCase("Clap!ClClaClap!ClaClap!CClap!ClClClap!CClaClap!CClap!ClClap!ClaClaClClap!ClaClap!ClClCClaClaCClaCCCCClClCClap!ClaCClaClCClap!Clap!ClaClaClaCClaClap!", Result =  52)]
    [TestCase("Clap!CClaClClap!ClCClCCClaCClap!ClCCClCClClap!ClClClap!CClap!CClCClap!ClCClap!Clap!Clap!Clap!ClClap!Clap!CClaClClap!ClaClaClaClCClClaClClap!ClaClClaClap!ClaClap!CClClClap!ClClaClClap!Clap!ClaClaClaClaClClap!CClaClClaCClap!ClClClClClap!Clap!CClClap!ClClap!ClaClap!CClClaClaClap!Clap!", Result =  97)]
    [TestCase("CClCClaCClap!Clap!ClaClap!ClCCClap!ClClClClap!ClaClCClClaClap!", Result =  23)]
    [TestCase("Clap!Clap!ClClCClCClClaClaClaCClaClClaClClClClap!CClap!ClClap!ClClClaClaClClaClaClaClaCClClaClap!", Result =  36)]
    [TestCase("ClaCCClClCClClaCClCClap!ClaClClaClap!Clap!ClClClClap!Clap!CClap!CClaClClaClCClaClap!ClaClaClaClap!Clap!ClClap!CCClap!ClClaClap!CClClClap!CClaClaClClaClap!ClClap!ClaCClaClap!Clap!Clap!Clap!CClaCCCClap!ClaClap!ClClap!Clap!CClaClaClaClap!CClaCClap!Clap!CClaCClaClaCClaCClap!", Result =  94)]
    [TestCase("CClClap!Clap!CClCClClaCClaClaClap!ClaClaClaCCCClap!CCClClap!Clap!ClaClaClap!ClClClap!ClCCClap!ClaClaClap!CClap!ClaClap!CClClClap!CClap!CClClaCClClap!ClaClap!ClaClClClCClap!ClaClClap!ClaClaCClap!CClClaClClap!ClaClaClClaClClaClaClap!", Result =  82)]
    [TestCase("ClaCCClCClaClClaClCClaClaClap!Clap!CClaClap!ClaClap!Clap!ClaClap!Clap!", Result =  23)]
    [TestCase("CClClaClClaClClap!Clap!Clap!ClClaClap!ClClClClaClap!CClap!ClaClaCCClap!ClClap!CClap!Clap!Clap!ClaClaClap!ClaClClClaClaClap!ClaClaClap!ClClCClaClaCClClaClap!Clap!Clap!CClClaClaClaClaClCClClaClaCClaClap!ClCClClClap!Clap!Clap!Clap!Clap!CClaClap!Clap!CCClaClCClClaClClClaClaClaClaCClap!Clap!", Result =  96)]
    [TestCase("Clap!ClaClCClaClap!ClCClap!ClClClaClap!ClaClaCClap!ClaClaClap!ClaCClap!Clap!CClClClap!ClClCClaCClCClaCClClClClaClap!ClClaCClap!CCCClap!Clap!ClClap!ClaCClaCClClap!ClClaClap!ClClaClaClaClaCCClClap!CClaClaClap!Clap!ClClap!", Result =  78)]
    [TestCase("Clap!ClaClCClaClaClap!CClaClap!CCClCClap!Clap!Clap!Clap!ClClap!Clap!ClaClaClClap!Clap!ClaClaClap!CClaClap!CCClClap!ClaClaClap!ClClaClaClaClaClap!CClap!ClaClCClaClap!CClClCClaClap!Clap!CClaCClap!", Result =  63)]
    [TestCase("Clap!CClaClap!ClClap!ClClClap!ClaCClap!ClaCClClap!CClap!CClClaClap!ClaClaClCCClap!Clap!CClClaClCClaClaClClap!Clap!CClaCClaCClap!ClaCClClCClap!CClap!CClap!ClaClaClaClaClap!ClClap!CClaClaClaClClaClClCClClCClClaClaCClClap!", Result =  80)]
    [TestCase("CClaCClClap!Clap!Clap!Clap!Clap!Clap!Clap!ClClClap!CClap!CClap!CCClaClClClClClaCClaClap!ClClap!CClaClap!Clap!CCClaClap!Clap!CClClClaClaClaClap!ClaCClap!ClClaClaCClClap!CClap!ClaClap!", Result =  60)]
    [TestCase("ClaCCClap!", Result =  4)]
    [TestCase("ClaClap!ClaClaClap!Clap!", Result =  6)]
    [TestCase("CClap!ClaClaClClap!Clap!ClaCCClap!ClClaClap!CClap!CClap!ClaClClaCClaClap!ClaClap!ClaClClaClaCCClClaClaClap!Clap!", Result =  37)]
    [TestCase("ClClaCClap!ClaCClaClap!Clap!Clap!ClaClClap!ClClaClaClClaClaClaCCClClClClClap!", Result =  27)]
    [TestCase("ClClClCClClap!Clap!CCCClap!ClCCClClap!CCClap!Clap!Clap!CClap!ClaClaCClaCClaClaClaClClap!ClaClCCClClaClap!ClClaClaCClCCClClClap!Clap!ClaClap!ClaClaCClap!ClCCClaClap!ClaClap!CClap!CClaClClaClCClaClap!CClClap!ClClap!Clap!CClap!CClaClaClClaClap!", Result =  88)]
    [TestCase("ClClCClClClaClClCClap!ClCClap!ClaClaClClap!ClaCClClap!ClClaClap!ClaClaClaClap!Clap!Clap!CCCClaClaClaClaClaCClCClaClaClap!Clap!CCCClap!ClaClap!CCClaClaClaClap!ClClClap!CClCCCClap!Clap!CClClClaClap!ClClaCClClap!ClaClClap!ClaClap!ClCClaClaCClap!", Result =  88)]
    [TestCase("ClClap!Clap!CCClClClaClClClClap!Clap!CClap!ClClap!ClClaCCClap!", Result =  22)]
    [TestCase("ClaClaClClClaCClap!ClaClaCCClaClaClClap!CClCClCClClClClap!ClaClap!Clap!ClaCCClap!ClCCClaClClClaCCClaClCClClaClap!ClClaClClaClap!ClClap!Clap!ClaClaClClap!", Result =  58)]
    [TestCase("ClaCClClClClaClClap!ClClap!CCClaCCClClCCClaClap!Clap!CClClClap!ClaCClClaCClaCClClap!ClClClClaCClaClap!Clap!", Result =  43)]
    [TestCase("ClaClCClClCClCClaCCClap!ClaClaCClap!ClaClap!CClaClaClClaCClClaClaClCCClaClap!ClClap!Clap!Clap!ClaCCClap!ClClaClaClap!ClaClap!CCClap!CClap!CClClap!", Result =  54)]
    [TestCase("Clap!ClaCCCCCClClaCCCClaClaClClap!CClaCClaCClap!CClap!CClCClClap!CCCCClaClap!", Result =  35)]
    [TestCase("ClClaClap!Clap!ClCClaClaCClaCClaClap!CCClaCClaClClap!Clap!ClCCCClaClaClap!Clap!ClaClap!ClaClClap!ClCClCClaClClap!CClaClap!ClClClaCClaCClap!Clap!ClCClCClap!ClaCCClClap!Clap!Clap!CClaClaClap!ClaCClaCClap!", Result =  73)]
    [TestCase("CClaClClaClap!ClClClaCClaClaCClCClCClaClaCClaClap!CCCCClap!ClaCClClaClClap!ClClClap!ClCClaClCClClClap!CClap!ClaClClap!ClCClap!", Result =  51)]
    [TestCase("ClaClaClaCClClap!ClaClap!Clap!ClCCCClaClap!Clap!CCClClClaClaCClClap!CClClaClClap!ClCCClaClClap!Clap!CClaCCCClClap!", Result =  44)]
    [TestCase("CClClap!ClClCClaClClaClaClap!ClaCClClaClaClaClaClap!ClClaClap!Clap!CClap!CClaClClap!ClClap!CClaClClap!ClaCCClap!CCClaClaClClClaClaClClap!CCClClaClClClClap!ClClap!ClaClClClap!Clap!CClaClaClaCClap!Clap!Clap!ClaClClClap!CClaClaClaClaClaCClClClaClap!ClClap!ClClaCClaClaCClClap!Clap!", Result =  98)]
    [TestCase("ClaCClaClap!CClap!ClClaClClaClaClaClCClaCClap!", Result =  17)]
    [TestCase("ClaClClap!", Result =  3)]
    [TestCase("ClClaClap!CClaCClClap!", Result =  8)]
    [TestCase("ClCClaClaClap!Clap!ClaCCClap!CClCClaClClap!CClClap!ClClCCCCClaCClClClaClClCClaClap!Clap!", Result =  36)]
    [TestCase("Clap!CClaCCCClClaClaClaClap!ClClaClClap!", Result =  15)]
    [TestCase("CClap!ClCCCCClClaClap!ClClClap!CClap!ClaClaClaClCCClCCClaClClap!Clap!CClaClClCClap!ClaClClap!ClCClaClaClap!", Result =  42)]
    [TestCase("Clap!ClaCClap!CCCCClaClap!ClClaCClClap!ClaClClap!ClaClClaClaClaClCCCClaClaCClap!Clap!ClaCCClap!ClClap!ClClap!ClClap!CClClClClap!Clap!CClaCClClClap!ClaCClClaCCClClap!CCClap!", Result =  65)]
    [TestCase("Clap!ClCClClap!CCClap!ClClap!ClClaClaClap!ClCClClClaClClap!ClCClap!Clap!Clap!ClCClap!ClCCClCClap!Clap!ClClCClCClap!ClCClaClaClCClap!", Result =  49)]
    [TestCase("ClCClap!ClaClap!CCClClCCClaClClCClaClClap!CClap!CClaClCClClap!ClClap!", Result =  28)]
    [TestCase("Clap!ClaClaCClap!", Result =  5)]
    [TestCase("ClClap!ClClap!ClaCCClap!ClClCClaClaClCClap!Clap!Clap!ClClaCClClaClap!Clap!ClClClClap!ClCCCClaClClap!Clap!ClClClap!ClaCClap!CClaClap!Clap!ClClClaClClClClaClaClClaClaClClClaCCClap!ClaClap!Clap!ClClClap!Clap!Clap!", Result =  72)]
    [TestCase("CClaCClCCClClClap!ClClaCCClap!Clap!Clap!ClClCClClClClaClaCClap!ClClClap!CClap!ClaClClaCCClClaClClap!CClCCCClaClaClCCClap!CClap!Clap!ClaClaClClaClClClaClaCClClap!Clap!CCClaClap!CClClaCClap!ClClClap!Clap!ClaClaClClClClap!Clap!ClaClap!", Result =  88)]
    [TestCase("CClClaCClaClClClaClaClap!Clap!ClaClaCClClaClaCClCClap!", Result =  21)]
    [TestCase("CClap!ClaClap!ClClap!CClaClClaClClap!CCClap!CClCCClap!CClap!Clap!ClClap!ClClap!Clap!ClClap!ClClClaClaCClaClaClCClap!ClaClap!CClap!ClaCClClap!Clap!Clap!Clap!ClClap!ClClClaCCClClap!ClaCCClaClCCClaClap!", Result =  69)]
    [TestCase("CClClap!Clap!ClCCClaClClCClClap!ClClClaCCClClaClaCClap!ClClap!Clap!ClClaClClClaCClaClClClaClClClaCClaClCClap!ClCCClClCClap!CCClClap!CClaClClap!ClCClClaClaClaClap!Clap!CClClap!ClaCClaClClClCClap!ClaClClClaClaCClaClap!", Result =  86)]
    [TestCase("Clap!Clap!ClClap!Clap!CClClaClaCClCClClap!ClClaCClClClCClaClClClaClClCClaCClClClap!ClaClap!ClClaClCCClaClaClaCCClaClap!", Result =  47)]
    [TestCase("ClaClaClClClap!Clap!ClClClClap!", Result =  10)]
    [TestCase("ClaClap!CClap!ClClClClap!CClaClClClap!CCClaClaClap!ClaClap!CClaCClClClaClap!ClClClClCClaCClap!ClClap!Clap!", Result =  38)]
    [TestCase("CCClaClClClClap!Clap!ClCCClClClaClCClCCClClap!", Result =  21)]
    [TestCase("ClClap!", Result =  2)]
    [TestCase("Clap!CCClClClaClap!ClaCClClap!CClClaClClaClap!Clap!ClaClap!", Result =  20)]
    [TestCase("ClaClap!CClaClaClap!CClClClap!ClCClap!Clap!Clap!", Result =  15)]
    [TestCase("ClaCClap!ClClap!ClaCClClaClap!Clap!Clap!", Result =  12)]
    [TestCase("ClClap!ClaClaCCClaClCClap!CClap!ClaClClaClap!CClClap!ClClap!ClaCClaCClaClaClCClaClaClaClClap!ClClap!CClaClap!Clap!CClap!ClCClap!ClaClaClap!ClaClap!ClClClCCClClaCCClaClClaClClClClaClClaClClap!ClaClap!CCClCClaCClClap!ClaClaClap!", Result =  83)]
    [TestCase("ClCClCClap!Clap!ClaClaClap!ClaCClClClap!ClaClaClaClap!ClClaClap!ClCCCClaCCClaClap!CClap!ClClap!ClaClap!CCCCClaClap!Clap!", Result =  43)]
    [TestCase("Clap!ClClClCClap!ClClap!ClClap!ClaClaClap!CClap!", Result =  15)]
    [TestCase("ClaClClap!ClCClaCClap!ClClap!CClaClap!CClClaCClaClap!CClaClaClaCCCCClap!CClaClaClClaClClap!ClClap!ClCClap!Clap!ClClap!CClClaClClap!CClaCClap!CClClap!ClaCClap!Clap!ClaClap!Clap!Clap!ClaClClap!Clap!Clap!ClClaClaClap!CClaClCClap!ClClClClaClaCClaClClClClap!", Result =  88)]
    [TestCase("ClClCClap!ClaClClaCCClaClaCClaClap!CClaClap!ClaCClClaClaClClap!ClaClaClClap!ClClCClaCClClap!", Result =  35)]
    [TestCase("ClaClClClap!Clap!ClClaClClaClaCClClaClap!ClaClClClaClClaClClaClClClaClCClaClap!CCCClap!Clap!CClap!Clap!ClaClap!CClap!ClClap!CClClClaClap!ClClCClaClClap!ClaClClaClaClCClClClap!ClClaClap!Clap!ClaCClClClaCClap!Clap!ClClaClClClClaClClap!ClClap!", Result =  85)]
    [TestCase("CClaClaClaClap!Clap!Clap!", Result =  7)]
    [TestCase("Clap!ClClClaClaClCClap!", Result =  8)]
    [TestCase("ClClap!Clap!Clap!CClCClap!Clap!Clap!CClClaCClap!ClaClap!Clap!ClClaClClCClap!", Result =  24)]
    [TestCase("ClCClap!ClaClaClap!CClap!Clap!ClaClap!ClaClClap!Clap!ClClaClap!ClClClaClaClaClaClaClaClap!", Result =  27)]
    [TestCase("CClap!ClaClClap!ClCClap!CClaCClClaClClap!CClap!CCCClClaClClap!CCClaClaClap!CCClap!Clap!Clap!Clap!ClClaCCCClaClClap!ClaClap!ClaClClaClap!Clap!ClaCClap!Clap!ClClClap!Clap!ClClaCClClaClap!Clap!Clap!ClCCClClap!Clap!ClCClCCClaClap!ClaCCClClClCCClClClaClaClap!Clap!ClaClaCClaClap!", Result =  98)]
    [TestCase("Clap!ClClClaCClap!CClap!ClaCClaClCClap!Clap!CClaCClCCClClClap!ClaClaCCCClClaCClaClClap!CClCClClap!Clap!CCClaClaClClaClaClap!Clap!ClCClaClaClClClap!Clap!ClaClClap!ClClClap!ClaClap!CCClap!ClaClap!ClClap!Clap!ClaClap!ClClClap!Clap!Clap!ClaCCClap!CClap!ClClaCClaClaClap!ClaCClap!ClaClCCClap!", Result =  101)]
    [TestCase("CCCCClClClap!ClaCClClClClaClClClaClClaClaClCCClap!ClClaCClap!CClap!Clap!ClaClap!Clap!Clap!", Result =  34)]
    [TestCase("ClClap!ClCClap!CClaClap!ClCClaCCClap!ClClap!CClap!CCClaClap!Clap!CClaClap!Clap!ClaClaClap!ClaClClClClaClCCCClap!CClap!CClap!CClaClClClClaClaClClClCClCClap!ClaCCClClClCCClClap!CClClap!Clap!ClaCClap!ClaClaCClaClap!ClaClaClap!", Result =  83)]
    [TestCase("Clap!Clap!Clap!ClClClCClClClap!Clap!Clap!ClClClClaClap!ClClClaClap!ClaClap!ClCClap!Clap!ClCClaCClClaClCCClClaCClCClCClaClap!Clap!CClaClap!ClClap!Clap!CCClap!CClaCClClClClap!ClClap!Clap!ClaClaClaCClap!ClClClap!Clap!Clap!", Result =  75)]
    [TestCase("Clap!ClaCClaClClap!ClCClaClClClap!ClClap!Clap!Clap!CClap!ClaClCClaClCClap!Clap!ClaClaClaClaClaClClap!CClCCClaCClap!ClaCClClaCCClClap!CClClCClaClap!ClaClCClCClap!ClaClCClClClap!ClClaClap!ClClap!ClCClaClClaCClaClaClClCClap!Clap!CClap!", Result =  86)]
    [TestCase("ClaCClap!ClClaCCClap!Clap!ClaClap!", Result =  11)]
    [TestCase("Clap!ClaClap!ClaClap!ClCClaClap!Clap!CCClaClaClap!ClaClaClap!ClClaCClClaCClaClClap!ClClClap!ClCClClCClap!Clap!", Result =  37)]
    [TestCase("ClClaClClaClaCClClap!ClaClaClaCClap!CCClClap!ClClaCClClaClaClaClap!ClaCCClaClaClap!ClaCClaClap!", Result =  35)]
    [TestCase("ClClaClClap!ClClaClap!Clap!ClaClClClap!ClaClap!ClaCCClap!Clap!ClClap!ClClaCClClCClClClaClap!ClClClCClaClap!CClap!ClClClap!ClCCClap!Clap!CClClCClaCClCClaClClap!CClaCCClap!CCClaClClap!ClaClClap!Clap!ClaClClap!ClaClaClap!Clap!ClaClap!ClClCClaCClaClClap!", Result =  89)]
    [TestCase("ClaClaClClap!ClaClCCClaClaCClap!CClCClap!Clap!", Result =  17)]
    [TestCase("CCClaCClap!ClClaClaClaClaClaClaCClaClap!Clap!CClClap!CClClaClap!Clap!ClClClaClaCClaCClaClClap!ClClClap!CClaClaClaClap!Clap!ClClap!Clap!ClaCClClClap!ClaClaClap!CCClClap!Clap!ClCCClClaClClCClap!ClaClap!", Result =  70)]
    [TestCase("ClCClaClap!ClClClClap!ClaClaCClaClClClap!CClCClCClClap!CClCClClClClaClCClap!CClaCCCCCClClap!ClaClaClaClClaClaClClaCClClap!Clap!CCClaClClaClap!ClCClap!CClClap!Clap!ClaClClap!CClaClaClap!CClClaClap!Clap!", Result =  78)]
    [TestCase("Clap!ClaClClCClaClCClaClClaClap!Clap!", Result =  13)]
    [TestCase("CClClap!Clap!CClaClap!ClaClap!ClCCClaClClap!ClaCClClaCClap!ClaClClClap!CClap!Clap!", Result =  28)]
    [TestCase("ClClaClap!CCClClClaCCClCClClap!ClaClCClaClClap!ClaClap!ClClaCClClaClaClaCClClaClap!ClClaClap!Clap!CCClClaClap!Clap!CClClClClClaClClCClClaCClap!Clap!ClaClaClCClap!Clap!ClaClaClClap!CClaCClaCClaClClaClap!CClap!ClCClap!CClCClaClaClClaClaClap!Clap!Clap!ClClaClap!Clap!", Result =  96)]
    [TestCase("ClaClap!ClaClCClClClClap!Clap!CClaClap!Clap!CCClaClaCClaCCCCClaClaClaCClClClaClap!ClClap!CClaCClClClap!ClaClCCCClap!ClClClaClClaClClap!", Result =  53)]
    [TestCase("ClClap!CClap!Clap!CClaCClClaCClClCClap!", Result =  15)]
    [TestCase("CClCClap!ClClap!ClCClaClap!Clap!CClaClaClaClClClap!", Result =  18)]
    [TestCase("ClaClCClaCClaClaClClaClClaClap!ClaCCClClaClap!Clap!CClap!ClCClap!CClClClap!ClClap!CClClap!", Result =  33)]
    [TestCase("ClaClap!ClClClap!ClClaClaCCCClaClClap!Clap!ClaClaClap!ClClap!Clap!CClap!Clap!CClClClap!ClaClCClap!Clap!ClClap!ClaCClap!Clap!", Result =  39)]
    [TestCase("ClClap!CCClap!ClClaClaCClCCClap!ClCCCClaClClaClap!ClClClaClClClaCCClaClap!Clap!Clap!ClCClaClaClap!ClaClCCClClClaClClClap!Clap!Clap!ClaCClap!ClClCClaClap!Clap!CClaClap!Clap!", Result =  63)]
    [TestCase("ClaClClCClClClap!ClaClaClap!Clap!ClClap!ClCClap!ClClap!ClaClap!ClaCClaClap!CClaClap!ClaClClaClaClap!ClClaClap!ClaCClap!CClClaCClap!Clap!CCClClCCCClClClClaCClClap!", Result =  58)]
    [TestCase("ClaClap!ClaClClap!ClCClClClaCClap!ClCClaClaClaClaClaCClap!ClClap!Clap!ClClaClCClap!ClaCClaClap!Clap!Clap!CClaCClClap!Clap!CClaClap!ClClClClaClap!ClaClap!", Result =  51)]
    [TestCase("ClCClCClCClClap!ClaClap!ClClaCCClCClaClaClap!CCClaClClap!ClClap!ClaClap!CClap!Clap!ClaClClaClap!Clap!ClClCClaClClClaClaClaClap!", Result =  46)]
    [TestCase("CClClClap!CCClap!CClap!Clap!CClClap!CCClaClClaCClap!ClaCClClCClap!Clap!CClap!ClaCClaClaClaClap!", Result =  35)]
    [TestCase("ClaCClaClap!CClCCClap!ClClap!CClap!Clap!ClCClCCCClCClap!ClaClClCCClaClap!", Result =  30)]
    [TestCase("CClaClClap!CClClClap!ClaClap!CClClClClaClaCCClaClaClap!Clap!Clap!ClaCClap!ClClCClap!ClaClClCCCClap!ClaClap!Clap!CCCCClaClap!CClap!Clap!ClaClClap!ClaClClaClClClap!Clap!", Result =  59)]
    [TestCase("ClClap!ClClaCClaCClap!CCCClap!Clap!ClClClap!Clap!Clap!ClCCClaClClCCClap!ClClap!CCClClap!ClaClap!ClaClap!ClCClap!Clap!ClaClCClClCClap!ClaCClCClap!Clap!Clap!ClClClClap!ClaCClaClaClCClClaClap!CClap!CCCCClaClap!ClaClap!", Result =  78)]
    [TestCase("ClClaClap!ClaClaClap!Clap!Clap!Clap!ClaClaClap!ClaCClaClap!ClClClap!Clap!CClaClap!CClClaClClCClap!ClaClap!ClClaClap!ClCCClaClCClap!ClCClClaClap!ClClaClap!Clap!Clap!Clap!ClCClap!ClClClaClap!Clap!Clap!ClaCClaClClaClCClClap!ClClCCClCClaClCClCCClClaClaClaClap!CClClClap!", Result =  92)]
    [TestCase("CClClap!ClClap!ClaClap!ClaCCCClaClaCClap!CClap!CClClaClap!CClap!ClClClaClClaClap!CClClaCClap!ClClaCClClaClap!CClap!CClClap!CClap!Clap!Clap!ClClClap!ClClaClap!CCClap!CCClCClCClCClaClaClClaClaClap!", Result =  72)]
    [TestCase("CCClaClap!CClaClClaClaCClaClClap!ClaCClCClaCClClClaClaCClaCCCClClap!ClaClaClaCClap!ClaClClaClClap!Clap!CClaCClap!CClClap!Clap!ClaCCClCClClap!ClaClaClaCCClaClaClaClCCClaClCClClap!", Result =  72)]
    [TestCase("ClCClap!ClaClaClCClap!CClap!Clap!ClClCCClClap!CCCClClClaClap!Clap!Clap!ClClaClClaClap!ClCCClaClap!CClClaCCClap!Clap!Clap!CClClaClap!Clap!ClaClCClap!ClCCClap!ClaClap!CCClaClap!CCClaClap!CClaClClaClaClaClap!Clap!CClap!Clap!Clap!Clap!ClClap!", Result =  82)]
    [TestCase("CClCCCCClap!CClap!Clap!CClap!ClaClaCCCClaClap!Clap!Clap!ClClap!CClaClaClaClaCClap!CClap!ClaCCClClaClClCCClaClaClCClaCCClap!", Result =  49)]
    [TestCase("ClClaClap!ClaCClaClaClap!Clap!CClClaClap!ClaClap!ClaClClaClaClap!ClaCClCCClaClaCClCClClap!ClCClap!ClClaClaClCClaClap!ClaClClaCCClap!ClaClap!ClClaClap!CClCClap!ClaClap!ClaClCClaClaCClap!ClClClap!Clap!CClClap!Clap!ClClaCClaCClaClap!Clap!CCClaClaClClap!Clap!ClCClClaClaClaClClClCClap!", Result =  100)]
    [TestCase("ClClap!ClCClClClap!CCClaCCCClaClCClClaClClClaClap!ClaClap!ClCClClap!ClaClap!ClaClClClap!ClCClaCClClap!ClClClClap!ClaClClaClap!ClClClaCClaClClaCClap!CClClap!ClaClap!Clap!ClaCClap!ClaClClap!CClClClaClCClaClaClaCClap!ClaClap!CClap!", Result =  84)]
    [TestCase("ClaClCClap!Clap!ClaClaClaClap!ClaClap!CClClap!ClaClCClaClClCCClClClClaClap!Clap!CClap!Clap!ClaCClaClClaCClap!ClClCCClaClClaClaCCClClap!Clap!CClaClap!CClap!ClClClap!ClaClaCClaCClClaClaClClaCClClap!ClCCClClap!ClCClap!CClaClaClap!Clap!ClaClap!ClCClaClap!Clap!", Result =  92)]
    [TestCase("ClCClap!Clap!Clap!ClaCClap!Clap!ClaClaClaClap!Clap!ClaClClap!", Result =  17)]
    [TestCase("ClClap!CClap!ClClaClaClClClClaClaClap!CCClaClaClaClap!ClClaClap!Clap!ClCClaCClap!ClClaCClaClap!Clap!ClaClaClap!ClaClap!CClap!ClCClap!ClClap!ClaClaClaClaClaClap!CClClClaCClap!CClaCCClaCClap!Clap!CCCClap!ClClClaCClap!Clap!ClaClClap!ClaClCClClap!", Result =  84)]
        public static int FixedTest(string a)
        {
            return Program.CountClaps(a);
        }
}

